#pragma once

#define YAML_LIB_VERSION_MAJOR 1
#define YAML_LIB_VERSION_MINOR 2
#define YAML_LIB_VERSION_PATCH 0
#define YAML_LIB_VERSION_STRING "1.2.0"

// Backward compatibility macros
#ifndef YAML_VERSION_MAJOR
#  define YAML_VERSION_MAJOR YAML_LIB_VERSION_MAJOR
#endif
#ifndef YAML_VERSION_MINOR
#  define YAML_VERSION_MINOR YAML_LIB_VERSION_MINOR
#endif
#ifndef YAML_VERSION_PATCH
#  define YAML_VERSION_PATCH YAML_LIB_VERSION_PATCH
#endif
